name: MLOps for Data Mining
on:
  push:
    branches:
      [features/development]

jobs:
  install_requirements:
    runs-on: [macos-latest]
    steps:
      - name: 'Installing requirements'
        run:
          pip install -r requirements.txt

  load_data:
    runs-on: [macos-latest]
    steps:
      - name: 'Load data'
        run:
          cd data
          python load_data.py
          #env:
          #  repo_token: ${{ secrets.GITHUB_TOKEN}}

