name: MLOps for Data Mining
on:
  push:
    branches:
      [features/development]

jobs:
  pipeline_ml_model:
      runs-on: [macos-latest]
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-python@v2
        - name: 'Installing requirements'
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        - name: 'Run ML pipeline'
          run: |
            python main.py --run_all