name: CI
on:
  push:
    branches:
      [features/development]

jobs:
  test:
    name: Test
      runs-on: [macos-latest]

    steps:
      - name: push a commit using the built-in token
      - uses: actions/checkout@v2
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
       

