name: CI
on:
  push:
    branches:
      [features/development]

jobs:
  check:
      runs-on: macos-latest
  steps:
    - name: 'test'
      uses: actions/checkout@v2
    - name: 'Setup pythoo'
      run:
        pip install python