name: MLOps for Data Mining
on:
  push:
    branches:
      [features/development]

jobs:
  pipeline_ml_model:
      runs-on: [macos-latest]
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-python@v2
        - name: 'Installing requirements'
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        - name: 'Load data'
          run: |
            cd data
            python load_data.py
            #env:
            #  repo_token: ${{ secrets.GITHUB_TOKEN}}
  
