name: MLOps for Data Mining
on:
  push:
    branches:
      [features/development]

jobs:
  load_data:
      runs-on: [macos-latest]
      steps:
        - name: 'Check out repository'
          run:
            pip install -r requirements.txt
            python data/load_data.py
          env:
            repo_token: ${{ secrets.GITHUB_TOKEN}}

