name: MLOps for Data Mining
on:
  push:
    branches:
      [features/development]

jobs:
    runs-on: [macos-latest]
    steps:
      - name: 'Installing requirements'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 'Load data'
        run: |
          cd data
          python load_data.py
          #env:
          #  repo_token: ${{ secrets.GITHUB_TOKEN}}

