name: Testing Actions
on:
  push:
    branches:
      [feature/pipeline]

jobs:
  testing_secret:
      runs-on: [macos-latest]
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-python@v2
        - name: 'Testing secrets'
          run: |
            python -m pip install --upgrade pip
            python test.py
          env:
            INPUT_DATA: ${{ secrets.INPUT_DATA }}